# Creating Quarto Book
# https://quarto.org/docs/books/
#
# options for Quarto book
# https://quarto.org/docs/reference/projects/books.html
#
# Options for html
# https://quarto.org/docs/reference/projects/websites.html#section

project:
  type: website
  output-dir: docs
  # resources:  # in case something was not included in rendered site automatically
  #   - "data/*"
  #   - "images/*"



number-depth: 2



website:
  title: "Welcome to my little notebook!"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: portfolio.qmd
        text: Portfolio
      - href: diary.qmd
        text: Diary

  search: true
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true

  cookie-consent:
    type: implied
    style: simple

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: style/custom.css
    toc: true
    toc-depth: 3
    link-external-newwindow: true
    fontsize: 1em
    smooth-scroll: true
    code-overflow: scroll
    code-copy: true
    code-link: true
    code-line-numbers: true
    code-block-bg: true
    code-block-border-left: "#1482FA"
    code-tools: true
    page-layout: full
    code-fold: true
    number-sections: false
    toc-expand: true

execute:
  echo: true
  warning: false
  error: false
  cache: false

editor:
  mode: source
  markdown:
    wrap: sentence
